### ISSUE TITLE
Map locations of all artwork in the ATEC building

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/research#1]
Identify the location on the maps below.

Level 1 
![atc1](https://cloud.githubusercontent.com/assets/1661430/6237379/f4150330-b6b7-11e4-948b-b3530a878932.png)

Level 2
![atc2](https://cloud.githubusercontent.com/assets/1661430/6237384/fa1dd8b0-b6b7-11e4-880f-cfd96c80c18f.png)

Level 3
![atc3](https://cloud.githubusercontent.com/assets/1661430/6237388/fbca9d06-b6b7-11e4-8d12-428a9ef25be7.png)

Level 4
![atc4](https://cloud.githubusercontent.com/assets/1661430/6237390/ff849320-b6b7-11e4-8d7f-460b6a94420b.png)

**Comment by cassininazir** [comment]
Use www.utdallas.edu/locator to identify room numbers.

**Comment by kelseeswenn** [comment]
Level 1- Purple
Level 2- Green
Level 3- Orange
Level 4-Blue

**Comment by kelseeswenn** [comment]
![atecmastermap](https://cloud.githubusercontent.com/assets/11038866/6405098/d39927d8-bde4-11e4-93ac-997b06f2887d.jpg)

**Comment by cassininazir** [comment]
Kelsee, great work. Mark this as closed. Could you also include the original file you used to edit (in case we need to make changes later)?
