### ISSUE TITLE
Description for pieces

### ISSUE THREAD

**Issue by judyn** [davidowproject/research#10]
I saw the google spreadsheet w/ the artist information, but still unsure of what should be should be put next to "Description". Description is included in the wireframes from UI, but do we have this information? Or should it be omitted/replaced with something else? @summersaylor @cassininazir thoughts?

![](http://ft.trillian.im/48a0cd6ab5ab67b43c361f24485eebba90331ece/6xNu8D7MCOvBDGOsxXdJLpBF3sLrl.jpg)

**Comment by summersaylor** [comment]
The word Description should not be placed, but instead just the description itself. Each art piece in the school has an info card next to it with information on it. The UI team assumed the cards had descriptions on them as well, at least for most of the pieces. I just looked at the collection online though and don't see any descriptions. If there are no descriptions then the question will take the description space.

@geoffreyvillalba @shruthiravi15 Are there descriptions on the info cards next to the art pieces in the school?

**Comment by shruthiravi15** [comment]
Yes there usually is. By description, are y’all asking what medium the artwork is? If so then yes it does have it in the infer cards by the piece.

**Comment by summersaylor** [comment]
No, description as in "This artwork was created to interpret blah blah
blah". We do call for Artist Name, Title of Piece, and Medium, as well as a
description.

**Comment by shruthiravi15** [comment]
Oh no, the artwork doesn’t have any description. Would you want a description to be added? The only issue that will come from that is that each artwork
will have a random description because not all of them are made to interpret something or made for specific reasons. Plus many artists are MIA so some may have a clear description and others will not have much at all.

**Comment by summersaylor** [comment]
Pass on the description then. I want all the art info screens to appear with the same type of information available. We may find a way to incorporate some of the artist bio and links yall have found, but that's tbd.

**Comment by shruthiravi15** [comment]
Ok. Let me know what all you need and I shall get you the info accordingly
