### ISSUE TITLE
Categorize art pieces

### ISSUE THREAD

**Issue by judyn** [davidowproject/research#4]
If you guys could please go through all the artwork and put them into categories, for example: sculpture, painting, mixed media etc., that would be really helpful!! You can also put a piece into multiple categories. 

http://www.utdallas.edu/davidow/list

Whoever can help out with this can upload the doc to the user research folder in Google Drive. Let me know if anyone has questions, thanks!!

**Comment by shruthiravi15** [comment]
Artwork Category

Mixed media:
Exquisite Corpse
Brown Cocoon Habitat
Untitled - Hart (German artist) 1994 mixed media drawings
untitledm [Desire] - Havel, Joseph  wood, fabric, foam core & plastic frame
The Mason’s Home
Time to Go
Double Bubble, World War II, Enlightenment #2
Untitled - Pomara, John  mixed media on canvas & wood (2 pieces)
Joni’s Chorus Line
Surprised Man
Time in a Bottle

Painting:
Texas Sky
Saved
Platitude
Study of Lies of Sound Memory
Central Control
Untitled - Jones, Otis  acrylic on wood
Untitled - Krapp, Jose Enrique 2004 Ink & graphite on paper, fr
Digital Landscape for #0002
Group
Untitled - Pomara, John 1991 enamel on canvas (dyptch)
Untitled - Ridgway, Linda 1999 2-color intaglio, ed 75 (2 pieces) 1 fr
Untitled - Schwarz, Ludwig 1996 acrylic on canvas
Chorus Line

Lithograph:
Unititled - Bodnar, Peter 2001 lithograph
Untitled - Jimenez, Lius 1997 lithograph 65/75
Untitled - Lawrence, Annette 2004 3-color etched lithograph, 40/75
Untitled - Rosenberg, Andrea 2005 black in lithograph, ed 75, fr
Celebrate

Sculpture:
Red
Untitled - Cole, Mark  polyurethane
Untitled - Dawe, Gabriel  cuff, pins in plexi cube
Placer
Tea For Two
Crown of Thorns
Etching on Paper
Endless House
Guardian Angels
Communication Quarterly 1978 & Southern Speech J, Vol 1954-55
Western Speech Vol J, 1976-79 & Central States Vol J 1978
Double Circles
Untitled - Hansen, Lily 2009 wood, fabric, cotton
Submersible
Wish! Angel
Aviation
After an Interval II
The X
Time Signature
Lubbock Housing Project #1
Seen Not Heard (Bouquet
White Box
The Beekeeper
You Quack me uo (1 of a cluster)
Tanya

Photograph:
Giggle
Moon over Wimberley
Fold #4
No One Would Believe She was Innocent
Unititled - Greenberg, Paul 1986 black & white photograph
Still Life with Fruit and Zhuang Zi
Untitled - McAn, Robert  holographic photograph on wood
Untitled - McAn, Robert  black-and-white photograph
Untitled - Murdoch, Annie 2000 color photograph
Last Chair
Frank Tolbert’s Mom’s Birthday
Untitled - Stautberg, Ann 2002 photogravure, 23/60
Untitled from series A Place Like Home - Yahav-Brown, Danny 2003 Duratrans light box, photograph, glass, 2 lights

```
Printing:
```

Untitled - Barber, Scott 2001 seriagraph
Dead
From North to South, East to West
Fingerprint I
By Lines (2)
The Temptation of St. Anthony xxvi, the Sun
Letting You Go
Untitled, (2) - Sotelo, Rudolfo Lailson 1988 intagl

**Comment by judyn** [comment]
thanks @shruthiravi15!
