### ISSUE TITLE
Find meta info for every artist

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/research#6]
Includes:
- Website
- Bio
- Social media
- Photo

**Comment by shruthiravi15** [comment]
Artists:
1.  Kelli Connel
2.  Kirsten Macy
3.  Tom Orr
4.  Laura Neaderhouser
5.  J Neil Lawley III
6.  Steve Wiman
7.  Mark Monroe
8.  Lawrence Jennings
9.  Ann Stautberg
10. John Hernandez
11. Chris Powell
12. Clyde Connell
13. Dean Ruck
14. Lily Hansen
15. Otis Jones
16. Linda Ridgway
17. Vernon Fisher
18. Jon Breazeale
19. Hiram Williams
20. Ann Wood
21. Fitzgerald
22. Hart
23. Joseph Havel
24. Harry Geffert
25. Aaron Baker
26. Linnea Glatt
27. Tracy Harris
28. Sally Glass
29. Ali Akbar
30. Peter Bodnar
31. Scott Barbar
32. Mark Cole
33. Linda Finnell
34. Nate Glaspie
35. Jose Enrique Krap
36. Gregory Metz
37. John Pomara
38. Jason Singleton
39. Jaune Smith
40. David Willburn
41. Ludwig Schwarz
42. Paul Slocum

**Comment by shruthiravi15** [comment]
Morgan: 1-11
Mithun: 12-21
@claudiaLopez23 Claudia: 22-32
@geoffreyvillalba eoffrey: 33-42

**Comment by shruthiravi15** [comment]
Completed Artist Info on google Drive under Research
