### ISSUE TITLE
Homepage Questions for each artwork

### ISSUE THREAD

**Issue by shruthiravi15** [davidowproject/research#8]
Provide 1-2 questions for each artwork. It can be a direct question with a specific answer or a thought provoking question that doesn't necessarily have an answer.

**Comment by summersaylor** [comment]
We are taking out the Home Page which means we need 2 questions per piece. They can be either with an answer, thought provoking, or both. We need only 2 per piece though and be sure to label which piece belongs to which questions.

**Comment by shruthiravi15** [comment]
The Questions for each art piece is in google Doc under Research folder --> Cue Questions on Artwork Folder -->Art Questions. On the map, there is a mistake on the Map IDs. For Level 4, it should be 32 and 33, not 31 and 32. We marked it as 32 & 33 on the Art Questions sheet.

**Comment by shruthiravi15** [comment]
assigned to @kelseeswenn @shruthiravi15 @geoffreyvillalba
