### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by shruthiravi15** [davidowproject/research#9]
Start documenting each part of the process for this whole project. Each phase should be documented with detail, starting from Phase 1 (Lance's beginning of this project) to Phase 2 (this current point within our Internet Studio Class). Within Phase 2 document each groups process (as much detail as possible) and all the groups process as a whole.

**Comment by shruthiravi15** [comment]
also assigned: @claudiaLopez23, Mithun

**Comment by cassininazir** [comment]
This should cover these four areas:

Problem/Overview
Process 
Craft
Impact

**Comment by claudiaLopez23** [comment]
Could you @dylanorgeron @summersaylor  write up a quick summary of what your group has been working on? We need to understand the process in order to document it properly on the website.

**Comment by summersaylor** [comment]
I wrote up a doc in the Drive, UI Group/Website Prep/ UI Project Documentation. It covers the 4 topics above and is a bit long, so I didn't post it here. Let me know if you need mas.

**Comment by shruthiravi15** [comment]
There were further parts to this issue which @Mithun completed regarding summaries for all 4 areas. The parts where we explained each document and design we came up with, I was able to complete that with the help of everyone as well. These are all in the google drive
